name: 'release-please'
on:
  push:
    branches:
      - 'main'
jobs:
  release-please:
    name: 'Release Please'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'main(simple)'
        uses: 'google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b' # 4.1.0
        with:
          default-branch: 'main'
          release-type: 'simple'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
