name: 'release-please'
on:
  push:
    branches:
      - 'main'
jobs:
  release-please:
    name: 'Release Please'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'main(simple)'
        uses: 'google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29' # 3.7.1
        with:
          default-branch: 'main'
          release-type: 'simple'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
