name: 'release-please'
on:
  push:
    branches:
      - 'main'
jobs:
  release-please:
    name: 'Release Please'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'main(simple)'
        uses: 'google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d' # 3.7.1
        with:
          default-branch: 'main'
          release-type: 'simple'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
